project:
  type: website

website:
  site-url: https://iqb-berlin.github.io/Quarto-Studio-Texte/
  title: "Quarto Texte Studio"
  favicon: favicon.ico
  back-to-top-navigation: true
  page-navigation: true
  repo-url: https://github.com/iqb-berlin/Quarto-Studio-Texte
  repo-actions: [issue]
  navbar:
    pinned: true
    search: true
    logo: IQB-klein.png
    background: '#536171'
  page-footer:
    border: true
    background: light
    right:
      - text: "IQB 2024"
        href: https://www.iqb.hu-berlin.de
    left:
      - text: "{{< fa house >}}"
        href: index.qmd
      - icon: github
        href: https://github.com/iqb-berlin/Quarto-Studio-Texte
        aria-label: Source Code
  sidebar:
    style: "floating"
    lang: de
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Schulungsinhalte
      - section: "Beispiele"
        href: Beispiele/index.qmd
        contents:
          - section: "Installation"
            href: Beispiele/install/index.qmd
            contents:
            - Beispiele/install/load-test.qmd
            - Beispiele/install/security.qmd
            - Beispiele/install/offline.qmd
          - section: "Daten und Prozesse"
            href: Beispiele/Daten_und_Prozesse/index.qmd
            contents:
            - Beispiele/Daten_und_Prozesse/Daten_Download.qmd
            - Beispiele/Daten_und_Prozesse/Daten_Upload.qmd
          - Beispiele/System_Check/index.qmd
          - Beispiele/Gruppenmonitor/index.qmd
          - section: "Studiendurchführung"
            href: Beispiele/Studiendurchfuehrung/index.qmd
            contents:
              - Beispiele/Studiendurchfuehrung/Vorbetrachtungen.qmd
              - Beispiele/Studiendurchfuehrung/Studienverhalten_konfigurieren.qmd
              - Beispiele/Studiendurchfuehrung/faq/index.qmd
          - Beispiele/faq/index.qmd
      - section: "Studio"
        href: Studio/index.qmd
        contents:
          - Studio/Arbeitsbereiche/index.qmd
          - section: "Aufgaben gestalten"
            href: Studio/Aufgaben_gestalten/index.qmd
            contents:
              - Studio/Aufgaben_gestalten/Andere_Editoren/index.qmd
              - Studio/Aufgaben_gestalten/Anlegen_von_Aufgaben_im_erweiterten_Modus/index.qmd
              - section: Anlegen von Aufgaben im Standardmodus
                href: Studio/Aufgaben_gestalten/Anlegen_von_Aufgaben_im_Standardmodus/index.qmd
                contents:
                  - Studio/Aufgaben_gestalten/Anlegen_von_Aufgaben_im_Standardmodus/Allgemeine_Anleitung/index.qmd
                  - Studio/Aufgaben_gestalten/Anlegen_von_Aufgaben_im_Standardmodus/Antwortfelder_Assistent/index.qmd
                  - Studio/Aufgaben_gestalten/Anlegen_von_Aufgaben_im_Standardmodus/Audio_ST_Assistent/index.qmd
                  - Studio/Aufgaben_gestalten/Anlegen_von_Aufgaben_im_Standardmodus/CMC-Assistent/index.qmd
                  - section: "Drag & Drop"
                    contents:
                    - Studio/Aufgaben_gestalten/Anlegen_von_Aufgaben_im_Standardmodus/DaD_Assistent_Sortieren/index.qmd
                    - Studio/Aufgaben_gestalten/Anlegen_von_Aufgaben_im_Standardmodus/DaD_Assistent_ZO_Einseitig_Elemente_neben_Ziel/index.qmd
                    - Studio/Aufgaben_gestalten/Anlegen_von_Aufgaben_im_Standardmodus/DaD_Assistent_ZO_Einseitig_Elemente_uber_Ziel/index.qmd
                  - Studio/Aufgaben_gestalten/Anlegen_von_Aufgaben_im_Standardmodus/GGB_Assistent/index.qmd
                  - Studio/Aufgaben_gestalten/Anlegen_von_Aufgaben_im_Standardmodus/Lueckentext_Verbundelement/index.qmd
                  - Studio/Aufgaben_gestalten/Anlegen_von_Aufgaben_im_Standardmodus/Markieren_Assistent/index.qmd
                  - Studio/Aufgaben_gestalten/Anlegen_von_Aufgaben_im_Standardmodus/MC_Bild_Assistent/index.qmd
                  - Studio/Aufgaben_gestalten/Anlegen_von_Aufgaben_im_Standardmodus/MC_Text_Assistent/index.qmd
                  - Studio/Aufgaben_gestalten/Anlegen_von_Aufgaben_im_Standardmodus/Nachtraegliches_Editieren/index.qmd
                  - Studio/Aufgaben_gestalten/Anlegen_von_Aufgaben_im_Standardmodus/Rechenkastchen_Assistent/index.qmd
                  - Studio/Aufgaben_gestalten/Anlegen_von_Aufgaben_im_Standardmodus/Tabellen_Assistent/index.qmd
                  - Studio/Aufgaben_gestalten/Anlegen_von_Aufgaben_im_Standardmodus/Text_ST_Assistent/index.qmd
                  - Studio/Aufgaben_gestalten/Glossar/Glossar.qmd
                  - Studio/Aufgaben_gestalten/IQB_Konventionen/index.qmd
          - Studio/FAQ/index.qmd
          - Studio/Installation/index.qmd
          - Studio/Kodierschema/index.qmd
    
format:
  html:
    theme: zephir
    css: styles.css
    toc: true
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
    code-overflow: scroll
    code-copy: true
    code-block-background: true
    highlight-style: ayu-dark
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
